Add checksum to file

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -41,6 +41,15 @@ jobs:
         run: |
           cp openspool-esp32s2/manifest.json firmware/manifest.json
           cp openspool-esp32s2/*.bin firmware/
+          for file in openspool-esp32s2/*.bin; do
+            md5 -q "$file" > "${file}.md5"
+            filelength=$(wc -c <"$file")
+            if [ "$filelength" -ne 3 ]; then
+              echo "md5 failed for $file"
+              exit 1
+            fi
+          done
+           
 
       - name: Commit manifest file
         uses: EndBug/add-and-commit@v9
@@ -48,7 +57,7 @@ jobs:
           committer_name: GitHub Actions
           committer_email: actions@github.com      
           message: Update manifest.json
-          add: "firmware/manifest.json firmware/*.bin"
+          add: "firmware/manifest.json firmware/*.bin firmware/*.md5"
           push: true
 
       - name: Upload Artifacts
